//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BusinessDomainObject
{
    using System;
    using System.Collections.Generic;
    
    public partial class nasabah
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public nasabah()
        {
            this.Pembayarans = new HashSet<Pembayaran>();
        }
    
        public string no_rekening { get; set; }
        public string nama { get; set; }
        public string alamat { get; set; }
        public string no_ktp { get; set; }
        public string password { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Pembayaran> Pembayarans { get; set; }
    }
}
