//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ItikAir
{
    using System;
    using System.Collections.Generic;
    
    public partial class penerbangan
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public penerbangan()
        {
            this.tiket = new HashSet<tiket>();
        }
    
        public int id_penerbangan { get; set; }
        public string nama_maskapai { get; set; }
        public string kota_asal { get; set; }
        public string kota_tujuan { get; set; }
        public System.DateTime tanggal_keberangkatan { get; set; }
        public string jam_keberangkatan { get; set; }
        public int harga { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tiket> tiket { get; set; }
    }
}
