//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication
{
    using System;
    using System.Collections.Generic;
    
    public partial class penerbangan
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public penerbangan()
        {
            this.bangkus = new HashSet<bangku>();
            this.tikets = new HashSet<tiket>();
        }
    
        public string no_pesawat { get; set; }
        public string bandara_asal { get; set; }
        public string bandara_tujuan { get; set; }
        public System.DateTime tgl_berangkat { get; set; }
        public System.DateTime tgl_tiba { get; set; }
        public System.TimeSpan jam_berangkat { get; set; }
        public System.TimeSpan jam_tiba { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<bangku> bangkus { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tiket> tikets { get; set; }
    }
}
