USE [master]
GO

/****** Object:  Database [BankKonservatif]    Script Date: 07/06/2020 13:00:34 ******/
CREATE DATABASE [BankKonservatif]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'BankKonservatif', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL12.MSSQLSERVER\MSSQL\DATA\BankKonservatif.mdf' , SIZE = 4096KB , MAXSIZE = UNLIMITED, FILEGROWTH = 1024KB )
 LOG ON 
( NAME = N'BankKonservatif_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL12.MSSQLSERVER\MSSQL\DATA\BankKonservatif_log.ldf' , SIZE = 1024KB , MAXSIZE = 2048GB , FILEGROWTH = 10%)
GO

ALTER DATABASE [BankKonservatif] SET COMPATIBILITY_LEVEL = 120
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [BankKonservatif].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [BankKonservatif] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [BankKonservatif] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [BankKonservatif] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [BankKonservatif] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [BankKonservatif] SET ARITHABORT OFF 
GO

ALTER DATABASE [BankKonservatif] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [BankKonservatif] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [BankKonservatif] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [BankKonservatif] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [BankKonservatif] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [BankKonservatif] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [BankKonservatif] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [BankKonservatif] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [BankKonservatif] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [BankKonservatif] SET  DISABLE_BROKER 
GO

ALTER DATABASE [BankKonservatif] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [BankKonservatif] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [BankKonservatif] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [BankKonservatif] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [BankKonservatif] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [BankKonservatif] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [BankKonservatif] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [BankKonservatif] SET RECOVERY FULL 
GO

ALTER DATABASE [BankKonservatif] SET  MULTI_USER 
GO

ALTER DATABASE [BankKonservatif] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [BankKonservatif] SET DB_CHAINING OFF 
GO

ALTER DATABASE [BankKonservatif] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [BankKonservatif] SET TARGET_RECOVERY_TIME = 0 SECONDS 
GO

ALTER DATABASE [BankKonservatif] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [BankKonservatif] SET  READ_WRITE 
GO

