USE [master]
GO

/****** Object:  Database [HotelMawarMelati]    Script Date: 02/06/2020 07:50:50 ******/
CREATE DATABASE [HotelMawarMelati]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'HotelMawarMelati', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL12.MSSQLSERVER\MSSQL\DATA\HotelMawarMelati.mdf' , SIZE = 4096KB , MAXSIZE = UNLIMITED, FILEGROWTH = 1024KB )
 LOG ON 
( NAME = N'HotelMawarMelati_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL12.MSSQLSERVER\MSSQL\DATA\HotelMawarMelati_log.ldf' , SIZE = 1024KB , MAXSIZE = 2048GB , FILEGROWTH = 10%)
GO

ALTER DATABASE [HotelMawarMelati] SET COMPATIBILITY_LEVEL = 120
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [HotelMawarMelati].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [HotelMawarMelati] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [HotelMawarMelati] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [HotelMawarMelati] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [HotelMawarMelati] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [HotelMawarMelati] SET ARITHABORT OFF 
GO

ALTER DATABASE [HotelMawarMelati] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [HotelMawarMelati] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [HotelMawarMelati] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [HotelMawarMelati] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [HotelMawarMelati] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [HotelMawarMelati] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [HotelMawarMelati] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [HotelMawarMelati] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [HotelMawarMelati] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [HotelMawarMelati] SET  DISABLE_BROKER 
GO

ALTER DATABASE [HotelMawarMelati] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [HotelMawarMelati] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [HotelMawarMelati] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [HotelMawarMelati] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [HotelMawarMelati] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [HotelMawarMelati] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [HotelMawarMelati] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [HotelMawarMelati] SET RECOVERY FULL 
GO

ALTER DATABASE [HotelMawarMelati] SET  MULTI_USER 
GO

ALTER DATABASE [HotelMawarMelati] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [HotelMawarMelati] SET DB_CHAINING OFF 
GO

ALTER DATABASE [HotelMawarMelati] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [HotelMawarMelati] SET TARGET_RECOVERY_TIME = 0 SECONDS 
GO

ALTER DATABASE [HotelMawarMelati] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [HotelMawarMelati] SET  READ_WRITE 
GO

