//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PuyuhAirDAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class penumpang
    {
        public int id_penumpang { get; set; }
        public int id_tiket { get; set; }
        public string nama { get; set; }
        public string nomor_identitas { get; set; }
    }
}
