//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Travelancar.maskapai_puyuh_air_service {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Pesawat", Namespace="http://schemas.datacontract.org/2004/07/PuyuhAir")]
    [System.SerializableAttribute()]
    public partial class Pesawat : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int hargaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int id_penerbanganField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string jam_keberangkatanField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string kota_asalField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string kota_tujuanField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string nama_maskapaiField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime tanggal_keberangkatanField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int harga {
            get {
                return this.hargaField;
            }
            set {
                if ((this.hargaField.Equals(value) != true)) {
                    this.hargaField = value;
                    this.RaisePropertyChanged("harga");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int id_penerbangan {
            get {
                return this.id_penerbanganField;
            }
            set {
                if ((this.id_penerbanganField.Equals(value) != true)) {
                    this.id_penerbanganField = value;
                    this.RaisePropertyChanged("id_penerbangan");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string jam_keberangkatan {
            get {
                return this.jam_keberangkatanField;
            }
            set {
                if ((object.ReferenceEquals(this.jam_keberangkatanField, value) != true)) {
                    this.jam_keberangkatanField = value;
                    this.RaisePropertyChanged("jam_keberangkatan");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string kota_asal {
            get {
                return this.kota_asalField;
            }
            set {
                if ((object.ReferenceEquals(this.kota_asalField, value) != true)) {
                    this.kota_asalField = value;
                    this.RaisePropertyChanged("kota_asal");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string kota_tujuan {
            get {
                return this.kota_tujuanField;
            }
            set {
                if ((object.ReferenceEquals(this.kota_tujuanField, value) != true)) {
                    this.kota_tujuanField = value;
                    this.RaisePropertyChanged("kota_tujuan");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string nama_maskapai {
            get {
                return this.nama_maskapaiField;
            }
            set {
                if ((object.ReferenceEquals(this.nama_maskapaiField, value) != true)) {
                    this.nama_maskapaiField = value;
                    this.RaisePropertyChanged("nama_maskapai");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime tanggal_keberangkatan {
            get {
                return this.tanggal_keberangkatanField;
            }
            set {
                if ((this.tanggal_keberangkatanField.Equals(value) != true)) {
                    this.tanggal_keberangkatanField = value;
                    this.RaisePropertyChanged("tanggal_keberangkatan");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="penerbangan", Namespace="http://schemas.datacontract.org/2004/07/PuyuhAir")]
    [System.SerializableAttribute()]
    public partial class penerbangan : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int hargaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int id_penerbanganField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string jam_keberangkatanField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string kota_asalField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string kota_tujuanField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string nama_maskapaiField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime tanggal_keberangkatanField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int harga {
            get {
                return this.hargaField;
            }
            set {
                if ((this.hargaField.Equals(value) != true)) {
                    this.hargaField = value;
                    this.RaisePropertyChanged("harga");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int id_penerbangan {
            get {
                return this.id_penerbanganField;
            }
            set {
                if ((this.id_penerbanganField.Equals(value) != true)) {
                    this.id_penerbanganField = value;
                    this.RaisePropertyChanged("id_penerbangan");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string jam_keberangkatan {
            get {
                return this.jam_keberangkatanField;
            }
            set {
                if ((object.ReferenceEquals(this.jam_keberangkatanField, value) != true)) {
                    this.jam_keberangkatanField = value;
                    this.RaisePropertyChanged("jam_keberangkatan");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string kota_asal {
            get {
                return this.kota_asalField;
            }
            set {
                if ((object.ReferenceEquals(this.kota_asalField, value) != true)) {
                    this.kota_asalField = value;
                    this.RaisePropertyChanged("kota_asal");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string kota_tujuan {
            get {
                return this.kota_tujuanField;
            }
            set {
                if ((object.ReferenceEquals(this.kota_tujuanField, value) != true)) {
                    this.kota_tujuanField = value;
                    this.RaisePropertyChanged("kota_tujuan");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string nama_maskapai {
            get {
                return this.nama_maskapaiField;
            }
            set {
                if ((object.ReferenceEquals(this.nama_maskapaiField, value) != true)) {
                    this.nama_maskapaiField = value;
                    this.RaisePropertyChanged("nama_maskapai");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime tanggal_keberangkatan {
            get {
                return this.tanggal_keberangkatanField;
            }
            set {
                if ((this.tanggal_keberangkatanField.Equals(value) != true)) {
                    this.tanggal_keberangkatanField = value;
                    this.RaisePropertyChanged("tanggal_keberangkatan");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="penumpang", Namespace="http://schemas.datacontract.org/2004/07/PuyuhAir")]
    [System.SerializableAttribute()]
    public partial class penumpang : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int id_penumpangField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int id_tiketField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string namaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string nomor_identitasField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int id_penumpang {
            get {
                return this.id_penumpangField;
            }
            set {
                if ((this.id_penumpangField.Equals(value) != true)) {
                    this.id_penumpangField = value;
                    this.RaisePropertyChanged("id_penumpang");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int id_tiket {
            get {
                return this.id_tiketField;
            }
            set {
                if ((this.id_tiketField.Equals(value) != true)) {
                    this.id_tiketField = value;
                    this.RaisePropertyChanged("id_tiket");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string nama {
            get {
                return this.namaField;
            }
            set {
                if ((object.ReferenceEquals(this.namaField, value) != true)) {
                    this.namaField = value;
                    this.RaisePropertyChanged("nama");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string nomor_identitas {
            get {
                return this.nomor_identitasField;
            }
            set {
                if ((object.ReferenceEquals(this.nomor_identitasField, value) != true)) {
                    this.nomor_identitasField = value;
                    this.RaisePropertyChanged("nomor_identitas");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CompositeType", Namespace="http://schemas.datacontract.org/2004/07/PuyuhAir")]
    [System.SerializableAttribute()]
    public partial class CompositeType : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Travelancar.maskapai_puyuh_air_service.penumpang[] daftarPenumpangField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Travelancar.maskapai_puyuh_air_service.penerbangan penerbangan_sahField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Travelancar.maskapai_puyuh_air_service.tiket tiket_sahField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Travelancar.maskapai_puyuh_air_service.penumpang[] daftarPenumpang {
            get {
                return this.daftarPenumpangField;
            }
            set {
                if ((object.ReferenceEquals(this.daftarPenumpangField, value) != true)) {
                    this.daftarPenumpangField = value;
                    this.RaisePropertyChanged("daftarPenumpang");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Travelancar.maskapai_puyuh_air_service.penerbangan penerbangan_sah {
            get {
                return this.penerbangan_sahField;
            }
            set {
                if ((object.ReferenceEquals(this.penerbangan_sahField, value) != true)) {
                    this.penerbangan_sahField = value;
                    this.RaisePropertyChanged("penerbangan_sah");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Travelancar.maskapai_puyuh_air_service.tiket tiket_sah {
            get {
                return this.tiket_sahField;
            }
            set {
                if ((object.ReferenceEquals(this.tiket_sahField, value) != true)) {
                    this.tiket_sahField = value;
                    this.RaisePropertyChanged("tiket_sah");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="tiket", Namespace="http://schemas.datacontract.org/2004/07/PuyuhAir")]
    [System.SerializableAttribute()]
    public partial class tiket : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string STATUSField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> batas_waktu_bayar_atmField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> batas_waktu_bayar_internet_bankingField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int id_penerbanganField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int id_tiketField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string kode_bayarField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string kode_bookingField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<long> total_hargaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> user_idField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> waktu_bookingField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string STATUS {
            get {
                return this.STATUSField;
            }
            set {
                if ((object.ReferenceEquals(this.STATUSField, value) != true)) {
                    this.STATUSField = value;
                    this.RaisePropertyChanged("STATUS");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> batas_waktu_bayar_atm {
            get {
                return this.batas_waktu_bayar_atmField;
            }
            set {
                if ((this.batas_waktu_bayar_atmField.Equals(value) != true)) {
                    this.batas_waktu_bayar_atmField = value;
                    this.RaisePropertyChanged("batas_waktu_bayar_atm");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> batas_waktu_bayar_internet_banking {
            get {
                return this.batas_waktu_bayar_internet_bankingField;
            }
            set {
                if ((this.batas_waktu_bayar_internet_bankingField.Equals(value) != true)) {
                    this.batas_waktu_bayar_internet_bankingField = value;
                    this.RaisePropertyChanged("batas_waktu_bayar_internet_banking");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int id_penerbangan {
            get {
                return this.id_penerbanganField;
            }
            set {
                if ((this.id_penerbanganField.Equals(value) != true)) {
                    this.id_penerbanganField = value;
                    this.RaisePropertyChanged("id_penerbangan");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int id_tiket {
            get {
                return this.id_tiketField;
            }
            set {
                if ((this.id_tiketField.Equals(value) != true)) {
                    this.id_tiketField = value;
                    this.RaisePropertyChanged("id_tiket");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string kode_bayar {
            get {
                return this.kode_bayarField;
            }
            set {
                if ((object.ReferenceEquals(this.kode_bayarField, value) != true)) {
                    this.kode_bayarField = value;
                    this.RaisePropertyChanged("kode_bayar");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string kode_booking {
            get {
                return this.kode_bookingField;
            }
            set {
                if ((object.ReferenceEquals(this.kode_bookingField, value) != true)) {
                    this.kode_bookingField = value;
                    this.RaisePropertyChanged("kode_booking");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<long> total_harga {
            get {
                return this.total_hargaField;
            }
            set {
                if ((this.total_hargaField.Equals(value) != true)) {
                    this.total_hargaField = value;
                    this.RaisePropertyChanged("total_harga");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> user_id {
            get {
                return this.user_idField;
            }
            set {
                if ((this.user_idField.Equals(value) != true)) {
                    this.user_idField = value;
                    this.RaisePropertyChanged("user_id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> waktu_booking {
            get {
                return this.waktu_bookingField;
            }
            set {
                if ((this.waktu_bookingField.Equals(value) != true)) {
                    this.waktu_bookingField = value;
                    this.RaisePropertyChanged("waktu_booking");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="maskapai_puyuh_air_service.PuyuhAirWebService")]
    public interface PuyuhAirWebService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/PuyuhAirWebService/GetPenerbangan", ReplyAction="http://tempuri.org/PuyuhAirWebService/GetPenerbanganResponse")]
        Travelancar.maskapai_puyuh_air_service.Pesawat[] GetPenerbangan();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/PuyuhAirWebService/GetPenerbangan", ReplyAction="http://tempuri.org/PuyuhAirWebService/GetPenerbanganResponse")]
        System.Threading.Tasks.Task<Travelancar.maskapai_puyuh_air_service.Pesawat[]> GetPenerbanganAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/PuyuhAirWebService/InsertPenerbangan", ReplyAction="http://tempuri.org/PuyuhAirWebService/InsertPenerbanganResponse")]
        void InsertPenerbangan(Travelancar.maskapai_puyuh_air_service.Pesawat penerbangan);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/PuyuhAirWebService/InsertPenerbangan", ReplyAction="http://tempuri.org/PuyuhAirWebService/InsertPenerbanganResponse")]
        System.Threading.Tasks.Task InsertPenerbanganAsync(Travelancar.maskapai_puyuh_air_service.Pesawat penerbangan);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/PuyuhAirWebService/UpdatePenerbangan", ReplyAction="http://tempuri.org/PuyuhAirWebService/UpdatePenerbanganResponse")]
        void UpdatePenerbangan(Travelancar.maskapai_puyuh_air_service.Pesawat penerbangan);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/PuyuhAirWebService/UpdatePenerbangan", ReplyAction="http://tempuri.org/PuyuhAirWebService/UpdatePenerbanganResponse")]
        System.Threading.Tasks.Task UpdatePenerbanganAsync(Travelancar.maskapai_puyuh_air_service.Pesawat penerbangan);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/PuyuhAirWebService/DeletePenerbangan", ReplyAction="http://tempuri.org/PuyuhAirWebService/DeletePenerbanganResponse")]
        void DeletePenerbangan(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/PuyuhAirWebService/DeletePenerbangan", ReplyAction="http://tempuri.org/PuyuhAirWebService/DeletePenerbanganResponse")]
        System.Threading.Tasks.Task DeletePenerbanganAsync(int id);
        
        // CODEGEN: Generating message contract since the wrapper name (getPenerbangan) of message getPenerbanganRequest does not match the default value (getPenerbangan1)
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/PuyuhAirWebService/getPenerbangan", ReplyAction="http://tempuri.org/PuyuhAirWebService/getPenerbanganResponse")]
        Travelancar.maskapai_puyuh_air_service.getPenerbanganResponse getPenerbangan1(Travelancar.maskapai_puyuh_air_service.getPenerbanganRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/PuyuhAirWebService/getPenerbangan", ReplyAction="http://tempuri.org/PuyuhAirWebService/getPenerbanganResponse")]
        System.Threading.Tasks.Task<Travelancar.maskapai_puyuh_air_service.getPenerbanganResponse> getPenerbangan1Async(Travelancar.maskapai_puyuh_air_service.getPenerbanganRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/PuyuhAirWebService/bayar", ReplyAction="http://tempuri.org/PuyuhAirWebService/bayarResponse")]
        int bayar(int id_tiket);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/PuyuhAirWebService/bayar", ReplyAction="http://tempuri.org/PuyuhAirWebService/bayarResponse")]
        System.Threading.Tasks.Task<int> bayarAsync(int id_tiket);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/PuyuhAirWebService/booking", ReplyAction="http://tempuri.org/PuyuhAirWebService/bookingResponse")]
        int booking(int id_penerbangan, Travelancar.maskapai_puyuh_air_service.penumpang[] penumpangs, int user_id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/PuyuhAirWebService/booking", ReplyAction="http://tempuri.org/PuyuhAirWebService/bookingResponse")]
        System.Threading.Tasks.Task<int> bookingAsync(int id_penerbangan, Travelancar.maskapai_puyuh_air_service.penumpang[] penumpangs, int user_id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/PuyuhAirWebService/getTiket", ReplyAction="http://tempuri.org/PuyuhAirWebService/getTiketResponse")]
        Travelancar.maskapai_puyuh_air_service.CompositeType getTiket(int id_tiket);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/PuyuhAirWebService/getTiket", ReplyAction="http://tempuri.org/PuyuhAirWebService/getTiketResponse")]
        System.Threading.Tasks.Task<Travelancar.maskapai_puyuh_air_service.CompositeType> getTiketAsync(int id_tiket);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/PuyuhAirWebService/getPemesanan", ReplyAction="http://tempuri.org/PuyuhAirWebService/getPemesananResponse")]
        Travelancar.maskapai_puyuh_air_service.tiket[] getPemesanan(int user_id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/PuyuhAirWebService/getPemesanan", ReplyAction="http://tempuri.org/PuyuhAirWebService/getPemesananResponse")]
        System.Threading.Tasks.Task<Travelancar.maskapai_puyuh_air_service.tiket[]> getPemesananAsync(int user_id);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getPenerbangan", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class getPenerbanganRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string kota_asal;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public string kota_tujuan;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=2)]
        public System.DateTime tanggal_keberangkatan;
        
        public getPenerbanganRequest() {
        }
        
        public getPenerbanganRequest(string kota_asal, string kota_tujuan, System.DateTime tanggal_keberangkatan) {
            this.kota_asal = kota_asal;
            this.kota_tujuan = kota_tujuan;
            this.tanggal_keberangkatan = tanggal_keberangkatan;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getPenerbanganResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class getPenerbanganResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public Travelancar.maskapai_puyuh_air_service.penerbangan[] getPenerbanganResult;
        
        public getPenerbanganResponse() {
        }
        
        public getPenerbanganResponse(Travelancar.maskapai_puyuh_air_service.penerbangan[] getPenerbanganResult) {
            this.getPenerbanganResult = getPenerbanganResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface PuyuhAirWebServiceChannel : Travelancar.maskapai_puyuh_air_service.PuyuhAirWebService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class PuyuhAirWebServiceClient : System.ServiceModel.ClientBase<Travelancar.maskapai_puyuh_air_service.PuyuhAirWebService>, Travelancar.maskapai_puyuh_air_service.PuyuhAirWebService {
        
        public PuyuhAirWebServiceClient() {
        }
        
        public PuyuhAirWebServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public PuyuhAirWebServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public PuyuhAirWebServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public PuyuhAirWebServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public Travelancar.maskapai_puyuh_air_service.Pesawat[] GetPenerbangan() {
            return base.Channel.GetPenerbangan();
        }
        
        public System.Threading.Tasks.Task<Travelancar.maskapai_puyuh_air_service.Pesawat[]> GetPenerbanganAsync() {
            return base.Channel.GetPenerbanganAsync();
        }
        
        public void InsertPenerbangan(Travelancar.maskapai_puyuh_air_service.Pesawat penerbangan) {
            base.Channel.InsertPenerbangan(penerbangan);
        }
        
        public System.Threading.Tasks.Task InsertPenerbanganAsync(Travelancar.maskapai_puyuh_air_service.Pesawat penerbangan) {
            return base.Channel.InsertPenerbanganAsync(penerbangan);
        }
        
        public void UpdatePenerbangan(Travelancar.maskapai_puyuh_air_service.Pesawat penerbangan) {
            base.Channel.UpdatePenerbangan(penerbangan);
        }
        
        public System.Threading.Tasks.Task UpdatePenerbanganAsync(Travelancar.maskapai_puyuh_air_service.Pesawat penerbangan) {
            return base.Channel.UpdatePenerbanganAsync(penerbangan);
        }
        
        public void DeletePenerbangan(int id) {
            base.Channel.DeletePenerbangan(id);
        }
        
        public System.Threading.Tasks.Task DeletePenerbanganAsync(int id) {
            return base.Channel.DeletePenerbanganAsync(id);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Travelancar.maskapai_puyuh_air_service.getPenerbanganResponse Travelancar.maskapai_puyuh_air_service.PuyuhAirWebService.getPenerbangan1(Travelancar.maskapai_puyuh_air_service.getPenerbanganRequest request) {
            return base.Channel.getPenerbangan1(request);
        }
        
        public Travelancar.maskapai_puyuh_air_service.penerbangan[] getPenerbangan1(string kota_asal, string kota_tujuan, System.DateTime tanggal_keberangkatan) {
            Travelancar.maskapai_puyuh_air_service.getPenerbanganRequest inValue = new Travelancar.maskapai_puyuh_air_service.getPenerbanganRequest();
            inValue.kota_asal = kota_asal;
            inValue.kota_tujuan = kota_tujuan;
            inValue.tanggal_keberangkatan = tanggal_keberangkatan;
            Travelancar.maskapai_puyuh_air_service.getPenerbanganResponse retVal = ((Travelancar.maskapai_puyuh_air_service.PuyuhAirWebService)(this)).getPenerbangan1(inValue);
            return retVal.getPenerbanganResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Travelancar.maskapai_puyuh_air_service.getPenerbanganResponse> Travelancar.maskapai_puyuh_air_service.PuyuhAirWebService.getPenerbangan1Async(Travelancar.maskapai_puyuh_air_service.getPenerbanganRequest request) {
            return base.Channel.getPenerbangan1Async(request);
        }
        
        public System.Threading.Tasks.Task<Travelancar.maskapai_puyuh_air_service.getPenerbanganResponse> getPenerbangan1Async(string kota_asal, string kota_tujuan, System.DateTime tanggal_keberangkatan) {
            Travelancar.maskapai_puyuh_air_service.getPenerbanganRequest inValue = new Travelancar.maskapai_puyuh_air_service.getPenerbanganRequest();
            inValue.kota_asal = kota_asal;
            inValue.kota_tujuan = kota_tujuan;
            inValue.tanggal_keberangkatan = tanggal_keberangkatan;
            return ((Travelancar.maskapai_puyuh_air_service.PuyuhAirWebService)(this)).getPenerbangan1Async(inValue);
        }
        
        public int bayar(int id_tiket) {
            return base.Channel.bayar(id_tiket);
        }
        
        public System.Threading.Tasks.Task<int> bayarAsync(int id_tiket) {
            return base.Channel.bayarAsync(id_tiket);
        }
        
        public int booking(int id_penerbangan, Travelancar.maskapai_puyuh_air_service.penumpang[] penumpangs, int user_id) {
            return base.Channel.booking(id_penerbangan, penumpangs, user_id);
        }
        
        public System.Threading.Tasks.Task<int> bookingAsync(int id_penerbangan, Travelancar.maskapai_puyuh_air_service.penumpang[] penumpangs, int user_id) {
            return base.Channel.bookingAsync(id_penerbangan, penumpangs, user_id);
        }
        
        public Travelancar.maskapai_puyuh_air_service.CompositeType getTiket(int id_tiket) {
            return base.Channel.getTiket(id_tiket);
        }
        
        public System.Threading.Tasks.Task<Travelancar.maskapai_puyuh_air_service.CompositeType> getTiketAsync(int id_tiket) {
            return base.Channel.getTiketAsync(id_tiket);
        }
        
        public Travelancar.maskapai_puyuh_air_service.tiket[] getPemesanan(int user_id) {
            return base.Channel.getPemesanan(user_id);
        }
        
        public System.Threading.Tasks.Task<Travelancar.maskapai_puyuh_air_service.tiket[]> getPemesananAsync(int user_id) {
            return base.Channel.getPemesananAsync(user_id);
        }
    }
}
