//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Bank_Konservatif.BankKonservatifService {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Pembayaran", Namespace="http://schemas.datacontract.org/2004/07/PembayaranService")]
    [System.SerializableAttribute()]
    public partial class Pembayaran : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string invoice_numberField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double nominalField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string norek_bayarField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int status_bayarField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime waktu_bayarField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime waktu_pesanField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string invoice_number {
            get {
                return this.invoice_numberField;
            }
            set {
                if ((object.ReferenceEquals(this.invoice_numberField, value) != true)) {
                    this.invoice_numberField = value;
                    this.RaisePropertyChanged("invoice_number");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double nominal {
            get {
                return this.nominalField;
            }
            set {
                if ((this.nominalField.Equals(value) != true)) {
                    this.nominalField = value;
                    this.RaisePropertyChanged("nominal");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string norek_bayar {
            get {
                return this.norek_bayarField;
            }
            set {
                if ((object.ReferenceEquals(this.norek_bayarField, value) != true)) {
                    this.norek_bayarField = value;
                    this.RaisePropertyChanged("norek_bayar");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int status_bayar {
            get {
                return this.status_bayarField;
            }
            set {
                if ((this.status_bayarField.Equals(value) != true)) {
                    this.status_bayarField = value;
                    this.RaisePropertyChanged("status_bayar");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime waktu_bayar {
            get {
                return this.waktu_bayarField;
            }
            set {
                if ((this.waktu_bayarField.Equals(value) != true)) {
                    this.waktu_bayarField = value;
                    this.RaisePropertyChanged("waktu_bayar");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime waktu_pesan {
            get {
                return this.waktu_pesanField;
            }
            set {
                if ((this.waktu_pesanField.Equals(value) != true)) {
                    this.waktu_pesanField = value;
                    this.RaisePropertyChanged("waktu_pesan");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="PembayaranFault", Namespace="http://schemas.datacontract.org/2004/07/PembayaranService")]
    [System.SerializableAttribute()]
    public partial class PembayaranFault : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FaultMessageField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FaultMessage {
            get {
                return this.FaultMessageField;
            }
            set {
                if ((object.ReferenceEquals(this.FaultMessageField, value) != true)) {
                    this.FaultMessageField = value;
                    this.RaisePropertyChanged("FaultMessage");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="BankKonservatifService.IPembayaranService")]
    public interface IPembayaranService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPembayaranService/getPembayaranByNorek", ReplyAction="http://tempuri.org/IPembayaranService/getPembayaranByNorekResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(Bank_Konservatif.BankKonservatifService.PembayaranFault), Action="http://tempuri.org/IPembayaranService/getPembayaranByNorekPembayaranFaultFault", Name="PembayaranFault", Namespace="http://schemas.datacontract.org/2004/07/PembayaranService")]
        Bank_Konservatif.BankKonservatifService.Pembayaran[] getPembayaranByNorek(string norek);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPembayaranService/getPembayaranByNorek", ReplyAction="http://tempuri.org/IPembayaranService/getPembayaranByNorekResponse")]
        System.Threading.Tasks.Task<Bank_Konservatif.BankKonservatifService.Pembayaran[]> getPembayaranByNorekAsync(string norek);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPembayaranService/DoPembayaran", ReplyAction="http://tempuri.org/IPembayaranService/DoPembayaranResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(Bank_Konservatif.BankKonservatifService.PembayaranFault), Action="http://tempuri.org/IPembayaranService/DoPembayaranPembayaranFaultFault", Name="PembayaranFault", Namespace="http://schemas.datacontract.org/2004/07/PembayaranService")]
        void DoPembayaran(string invoiceNum, string norek);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPembayaranService/DoPembayaran", ReplyAction="http://tempuri.org/IPembayaranService/DoPembayaranResponse")]
        System.Threading.Tasks.Task DoPembayaranAsync(string invoiceNum, string norek);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IPembayaranServiceChannel : Bank_Konservatif.BankKonservatifService.IPembayaranService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class PembayaranServiceClient : System.ServiceModel.ClientBase<Bank_Konservatif.BankKonservatifService.IPembayaranService>, Bank_Konservatif.BankKonservatifService.IPembayaranService {
        
        public PembayaranServiceClient() {
        }
        
        public PembayaranServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public PembayaranServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public PembayaranServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public PembayaranServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public Bank_Konservatif.BankKonservatifService.Pembayaran[] getPembayaranByNorek(string norek) {
            return base.Channel.getPembayaranByNorek(norek);
        }
        
        public System.Threading.Tasks.Task<Bank_Konservatif.BankKonservatifService.Pembayaran[]> getPembayaranByNorekAsync(string norek) {
            return base.Channel.getPembayaranByNorekAsync(norek);
        }
        
        public void DoPembayaran(string invoiceNum, string norek) {
            base.Channel.DoPembayaran(invoiceNum, norek);
        }
        
        public System.Threading.Tasks.Task DoPembayaranAsync(string invoiceNum, string norek) {
            return base.Channel.DoPembayaranAsync(invoiceNum, norek);
        }
    }
}
