//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.ComponentModel;
using System.Data.EntityClient;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Linq;
using System.Runtime.Serialization;
using System.Xml.Serialization;

[assembly: EdmSchemaAttribute()]
#region EDM Relationship Metadata

[assembly: EdmRelationshipAttribute("HotelMawarMelatiModel", "FK_kamar_booking", "booking", System.Data.Metadata.Edm.RelationshipMultiplicity.ZeroOrOne, typeof(HotelKasurDBO.booking), "kamar", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(HotelKasurDBO.kamar), true)]

#endregion

namespace HotelKasurDBO
{
    #region Contexts
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    public partial class HotelMawarMelatiEntities : ObjectContext
    {
        #region Constructors
    
        /// <summary>
        /// Initializes a new HotelMawarMelatiEntities object using the connection string found in the 'HotelMawarMelatiEntities' section of the application configuration file.
        /// </summary>
        public HotelMawarMelatiEntities() : base("name=HotelMawarMelatiEntities", "HotelMawarMelatiEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new HotelMawarMelatiEntities object.
        /// </summary>
        public HotelMawarMelatiEntities(string connectionString) : base(connectionString, "HotelMawarMelatiEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new HotelMawarMelatiEntities object.
        /// </summary>
        public HotelMawarMelatiEntities(EntityConnection connection) : base(connection, "HotelMawarMelatiEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region Partial Methods
    
        partial void OnContextCreated();
    
        #endregion
    
        #region ObjectSet Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<booking> bookings
        {
            get
            {
                if ((_bookings == null))
                {
                    _bookings = base.CreateObjectSet<booking>("bookings");
                }
                return _bookings;
            }
        }
        private ObjectSet<booking> _bookings;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<kamar> kamars
        {
            get
            {
                if ((_kamars == null))
                {
                    _kamars = base.CreateObjectSet<kamar>("kamars");
                }
                return _kamars;
            }
        }
        private ObjectSet<kamar> _kamars;

        #endregion

        #region AddTo Methods
    
        /// <summary>
        /// Deprecated Method for adding a new object to the bookings EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddTobookings(booking booking)
        {
            base.AddObject("bookings", booking);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the kamars EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddTokamars(kamar kamar)
        {
            base.AddObject("kamars", kamar);
        }

        #endregion

    }

    #endregion

    #region Entities
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="HotelMawarMelatiModel", Name="booking")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class booking : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new booking object.
        /// </summary>
        /// <param name="kode_booking">Initial value of the kode_booking property.</param>
        public static booking Createbooking(global::System.String kode_booking)
        {
            booking booking = new booking();
            booking.kode_booking = kode_booking;
            return booking;
        }

        #endregion

        #region Simple Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String kode_booking
        {
            get
            {
                return _kode_booking;
            }
            set
            {
                if (_kode_booking != value)
                {
                    Onkode_bookingChanging(value);
                    ReportPropertyChanging("kode_booking");
                    _kode_booking = StructuralObject.SetValidValue(value, false, "kode_booking");
                    ReportPropertyChanged("kode_booking");
                    Onkode_bookingChanged();
                }
            }
        }
        private global::System.String _kode_booking;
        partial void Onkode_bookingChanging(global::System.String value);
        partial void Onkode_bookingChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> tanggal_mulai
        {
            get
            {
                return _tanggal_mulai;
            }
            set
            {
                Ontanggal_mulaiChanging(value);
                ReportPropertyChanging("tanggal_mulai");
                _tanggal_mulai = StructuralObject.SetValidValue(value, "tanggal_mulai");
                ReportPropertyChanged("tanggal_mulai");
                Ontanggal_mulaiChanged();
            }
        }
        private Nullable<global::System.DateTime> _tanggal_mulai;
        partial void Ontanggal_mulaiChanging(Nullable<global::System.DateTime> value);
        partial void Ontanggal_mulaiChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> tanggal_selesai
        {
            get
            {
                return _tanggal_selesai;
            }
            set
            {
                Ontanggal_selesaiChanging(value);
                ReportPropertyChanging("tanggal_selesai");
                _tanggal_selesai = StructuralObject.SetValidValue(value, "tanggal_selesai");
                ReportPropertyChanged("tanggal_selesai");
                Ontanggal_selesaiChanged();
            }
        }
        private Nullable<global::System.DateTime> _tanggal_selesai;
        partial void Ontanggal_selesaiChanging(Nullable<global::System.DateTime> value);
        partial void Ontanggal_selesaiChanged();

        #endregion

        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("HotelMawarMelatiModel", "FK_kamar_booking", "kamar")]
        public EntityCollection<kamar> kamars
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<kamar>("HotelMawarMelatiModel.FK_kamar_booking", "kamar");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<kamar>("HotelMawarMelatiModel.FK_kamar_booking", "kamar", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="HotelMawarMelatiModel", Name="kamar")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class kamar : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new kamar object.
        /// </summary>
        /// <param name="id">Initial value of the id property.</param>
        /// <param name="no_kamar">Initial value of the no_kamar property.</param>
        public static kamar Createkamar(global::System.String id, global::System.String no_kamar)
        {
            kamar kamar = new kamar();
            kamar.id = id;
            kamar.no_kamar = no_kamar;
            return kamar;
        }

        #endregion

        #region Simple Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String id
        {
            get
            {
                return _id;
            }
            set
            {
                if (_id != value)
                {
                    OnidChanging(value);
                    ReportPropertyChanging("id");
                    _id = StructuralObject.SetValidValue(value, false, "id");
                    ReportPropertyChanged("id");
                    OnidChanged();
                }
            }
        }
        private global::System.String _id;
        partial void OnidChanging(global::System.String value);
        partial void OnidChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String no_kamar
        {
            get
            {
                return _no_kamar;
            }
            set
            {
                Onno_kamarChanging(value);
                ReportPropertyChanging("no_kamar");
                _no_kamar = StructuralObject.SetValidValue(value, false, "no_kamar");
                ReportPropertyChanged("no_kamar");
                Onno_kamarChanged();
            }
        }
        private global::System.String _no_kamar;
        partial void Onno_kamarChanging(global::System.String value);
        partial void Onno_kamarChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Double> harga_akhir_pekan
        {
            get
            {
                return _harga_akhir_pekan;
            }
            set
            {
                Onharga_akhir_pekanChanging(value);
                ReportPropertyChanging("harga_akhir_pekan");
                _harga_akhir_pekan = StructuralObject.SetValidValue(value, "harga_akhir_pekan");
                ReportPropertyChanged("harga_akhir_pekan");
                Onharga_akhir_pekanChanged();
            }
        }
        private Nullable<global::System.Double> _harga_akhir_pekan;
        partial void Onharga_akhir_pekanChanging(Nullable<global::System.Double> value);
        partial void Onharga_akhir_pekanChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Double> harga_biasa
        {
            get
            {
                return _harga_biasa;
            }
            set
            {
                Onharga_biasaChanging(value);
                ReportPropertyChanging("harga_biasa");
                _harga_biasa = StructuralObject.SetValidValue(value, "harga_biasa");
                ReportPropertyChanged("harga_biasa");
                Onharga_biasaChanged();
            }
        }
        private Nullable<global::System.Double> _harga_biasa;
        partial void Onharga_biasaChanging(Nullable<global::System.Double> value);
        partial void Onharga_biasaChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String fasilitas
        {
            get
            {
                return _fasilitas;
            }
            set
            {
                OnfasilitasChanging(value);
                ReportPropertyChanging("fasilitas");
                _fasilitas = StructuralObject.SetValidValue(value, true, "fasilitas");
                ReportPropertyChanged("fasilitas");
                OnfasilitasChanged();
            }
        }
        private global::System.String _fasilitas;
        partial void OnfasilitasChanging(global::System.String value);
        partial void OnfasilitasChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String status_tersedia
        {
            get
            {
                return _status_tersedia;
            }
            set
            {
                Onstatus_tersediaChanging(value);
                ReportPropertyChanging("status_tersedia");
                _status_tersedia = StructuralObject.SetValidValue(value, true, "status_tersedia");
                ReportPropertyChanged("status_tersedia");
                Onstatus_tersediaChanged();
            }
        }
        private global::System.String _status_tersedia;
        partial void Onstatus_tersediaChanging(global::System.String value);
        partial void Onstatus_tersediaChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> kapasitas
        {
            get
            {
                return _kapasitas;
            }
            set
            {
                OnkapasitasChanging(value);
                ReportPropertyChanging("kapasitas");
                _kapasitas = StructuralObject.SetValidValue(value, "kapasitas");
                ReportPropertyChanged("kapasitas");
                OnkapasitasChanged();
            }
        }
        private Nullable<global::System.Int32> _kapasitas;
        partial void OnkapasitasChanging(Nullable<global::System.Int32> value);
        partial void OnkapasitasChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String kode_booking
        {
            get
            {
                return _kode_booking;
            }
            set
            {
                Onkode_bookingChanging(value);
                ReportPropertyChanging("kode_booking");
                _kode_booking = StructuralObject.SetValidValue(value, true, "kode_booking");
                ReportPropertyChanged("kode_booking");
                Onkode_bookingChanged();
            }
        }
        private global::System.String _kode_booking;
        partial void Onkode_bookingChanging(global::System.String value);
        partial void Onkode_bookingChanged();

        #endregion

        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("HotelMawarMelatiModel", "FK_kamar_booking", "booking")]
        public booking booking
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<booking>("HotelMawarMelatiModel.FK_kamar_booking", "booking").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<booking>("HotelMawarMelatiModel.FK_kamar_booking", "booking").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<booking> bookingReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<booking>("HotelMawarMelatiModel.FK_kamar_booking", "booking");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<booking>("HotelMawarMelatiModel.FK_kamar_booking", "booking", value);
                }
            }
        }

        #endregion

    }

    #endregion

}
