//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HotelKasurDBO
{
    using System;
    using System.Collections.Generic;
    
    public partial class kamar
    {
        public string id { get; set; }
        public string no_kamar { get; set; }
        public Nullable<double> harga_akhir_pekan { get; set; }
        public Nullable<double> harga_biasa { get; set; }
        public string fasilitas { get; set; }
        public string status_tersedia { get; set; }
        public Nullable<int> kapasitas { get; set; }
        public string kode_booking { get; set; }
    
        public virtual booking booking { get; set; }
    }
}
