//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Bank_Konservatif.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class nasabah
    {
        public string no_rekening { get; set; }
        public string nama { get; set; }
        public string alamat { get; set; }
        public string no_ktp { get; set; }
        public string password { get; set; }
        public Nullable<double> saldo { get; set; }
    }
}
