//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BusinessDomainObject
{
    using System;
    using System.Collections.Generic;
    
    public partial class Booking
    {
        public string kode_booking { get; set; }
        public string id_user { get; set; }
        public System.DateTime tanggal_booking { get; set; }
        public System.DateTime tanggal_mulai { get; set; }
        public System.DateTime tanggal_selesai { get; set; }
    }
}
