//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BusinessDomainObject
{
    using System;
    using System.Collections.Generic;
    
    public partial class BookingHistory
    {
        public string kode_booking { get; set; }
        public string id_kamar { get; set; }
    
        public virtual BookingHistory BookingHistory1 { get; set; }
        public virtual BookingHistory BookingHistory2 { get; set; }
    }
}
