//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BusinessDomainObject
{
    using System;
    using System.Collections.Generic;
    
    public partial class Kamar
    {
        public string id { get; set; }
        public string no_kamar { get; set; }
        public double harga_akhir_pekan { get; set; }
        public double harga_biasa { get; set; }
        public string fasilitas { get; set; }
        public int kapasitas { get; set; }
        public int status { get; set; }
    }
}
